### ISSUE TITLE
Reusable grunt task for plugins

### ISSUE THREAD

**Issue by thijstriemstra** [videojs/font#17]
Plugin authors can add buttons and other elements that contain custom icons. Currently I've copied most of the code in this repository in order to produce a custom font. Is it possible to make a reusable plugin that is also compatible with non-ES6 code? I'm willing to help with a PR but some guidance would be useful.

**Comment by gkatsev** [comment]
We use webfonts-generator to generate the font files. I'm not sure there's a lot extra stuff in this repo that isn't specific to us.
Or do you mean specifically abstracting out the grunt task we use with the webfonts-generator module?

**Comment by thijstriemstra** [comment]
> Or do you mean specifically abstracting out the grunt task we use with the webfonts-generator module?

Yeah like the videojs-language grunt task.

**Comment by thijstriemstra** [comment]
Perhaps a reusable grunt task is overkill and a custom `icons.json` should be enough?

I wrote down the steps to update the font for one of my plugins to give you an idea what's required at the moment: https://github.com/collab-project/videojs-record/blob/master/font/README.md

**Comment by gkatsev** [comment]
Would #24 be sufficient for this?

**Comment by thijstriemstra** [comment]
@gkatsev yep.
