### ISSUE TITLE
add download icon from Material Design

### ISSUE THREAD

**Issue by rpmansion** [videojs/font#18]
Hi,

Please add the download icon from Material Design.

Thanks,
Robert

**Comment by gkatsev** [comment]
Can you please provide more information on the usecase? We want to try and keep this limited to the bare minimum that would be used by videojs and possibly plugins.

**Comment by rpmansion** [comment]
Hi,

We added a custom button on videojs where we allow user to download the video on their local machine.

**Comment by mmcc** [comment]
Hi there, you can definitely use this repo to add that icon for your own purposes, but as @gkatsev said, the point is to keep the official font we distribute with Video.js to the absolute bare minimum.
