### ISSUE TITLE
video js close font not working 

### ISSUE THREAD

**Issue by mahesfsp** [videojs/font#22]
need a close button without background. can you please add the close button font for video js?

**Comment by mmcc** [comment]
Did you have a specific icon in mind? I assume you mean something like [ic_close](https://material.io/icons/#ic_close)? You could build a custom font yourself pretty easily, you just need to add that icon to [icons.json](https://github.com/videojs/font/blob/master/icons.json) and rebuild.

Without adding a new icon to the font, there also [quite a few x options out there](http://stackoverflow.com/questions/5353461/which-font-for-css-x-close-button). Would something like that work for you?

**Comment by mahesfsp** [comment]
yes , I have used HTML code &times for close button. Thanks
