### ISSUE TITLE
pause icon not display on android 4.2

### ISSUE THREAD

**Issue by oanhnn** [videojs/font#9]
I using videojs 5.3.0 on a webview of android 4.2.
Pause icon dose not display, but play icon, volume mute icon is display.
I changed css file, using volume icon instead pause icon and it is displayed.
Please check thi problem.

**Comment by gkatsev** [comment]
I'm not sure this is a problem. I'm able to see it on android.
Closing this issue. If it is still a problem and we get more information and a reduced test case, we will happily re-open the issue.
